name: GitHub Actions Demo
on:
  pull_request:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by a ${{ github.event_name }} event to the ${{ github.ref }} branch."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Run tests
        run: |
          python3 meal_app/meal_app/test_file.py
      - run: echo "Job status - ${{ job.status }}."